version: '3'
services:
  node:
    image: node:8
    volumes:
      - .:/var/app
    working_dir: /var/app
  postgres:
    image: alpine
    ports: ['5432']
    command: nc -l 5432
  postgres-test:
    image: alpine
    ports: ['5432']
    command: nc -l 5432
  rabbit-mq:
    image: alpine
    ports: ['5672', '15672']
    command: nc -l 5672 15672
